/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_xxl_example_MainActivity */

#ifndef _Included_com_xxl_example_MainActivity
#define _Included_com_xxl_example_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xxl_example_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xxl_example_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
